import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import copy from 'esbuild-plugin-copy';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const staticAssetsPlugin = {
  name: 'static-assets-plugin',
  setup(build) {
    build.onLoad({ filter: /.+/ }, (args) => {
      return {
        watchFiles: ['styles.css', 'esbuild.config.mjs'],
      };
    });
  },
};

const prod = process.argv[2] === "production";

esbuild
  .build({
    banner: {
      js: banner,
    },
    minify: prod ? true : false,
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "codemirror",
      "@codemirror/view",
      ...builtins,
    ],
    format: "cjs",
    watch: !prod,
    target: "ES2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "dist/main.js",
    plugins: [
      staticAssetsPlugin,
      copy.default({
        verbose: false,
        assets: {
          from: ['manifest*', 'styles.css'],
          to: ['.'],
        }
      }),
    ],
  })
  .catch(() => process.exit(1));
